# TCP Sample Profile
netcat test:
  mode: tcp
  
  # WiFi SSID for the managed network
  wifi_ssid: wifiSSID
  # WiFi password
  wifi_password: wifiPassword
  # Leave it empty for DHCP or enter static IP if needed
  wifi_ip:

  # Remote TCP Host IP Address
  remote_ip: ipAddress
  # Remote TCP Host port
  remote_port: tcpPort

  # Keyboard mapping, buttons follow playstation layout
  # - Each entry is optional, an empty entry ("a: ") is like omitting it entirely
  # - NULL or missing entries ("a: ") are ignored, no event will be transmitted
  # - Playstation mapping layout
  # - Each single profile has its own dedicated mapping
  # - System button (start in PS layout) cannot be remapped
  # See samples here to understand how it works
  map:
    a:    # When empty is totally ignored, the key will not be transmitted
    b: b
    x: x\x0d\x0a
    y: yY\x0d\x0a
    menu: \x1bOP        # F1
    option: \x1bOQ      # F2
    right_top:
    right_bottom:
    dpad_left:
    dpad_right:
    dpad_up:
    dpad_down:
    select:
    left_top:
    left_bottom:
